### 사용 한도, 현재 소비량, 남은 할당량을 반환하며, 지정된 날짜 범위에 따라 선택적으로 필터링합니다.
GET https://soundtracks.loudly.com/api/account/limits
Accept: application/json
API-KEY: 8fHIM8Z_kToH_3asmw7yFaZ6fGW2oRldjQavGCnhj6g


### AI 노래 생성에 사용할 수 있는 장르 목록을 반환합니다. 이 엔드포인트는 POST /api/ai/song 값을 선택하는 데 도움이 됩니다.
GET https://soundtracks.loudly.com/api/ai/genres
Accept: application/json
API-KEY: 8fHIM8Z_kToH_3asmw7yFaZ6fGW2oRldjQavGCnhj6g
